### ISSUE TITLE
FineTuningTask's pretrained_checkpoint should be configurable

### ISSUE THREAD

**Issue by miguelvr** [facebookresearch/ClassyVision#340]
## 🚀 Feature
It seems logical to me that the `set_pretrained_checkpoint` argument from the fine tuning task should be present in the config. 

## Motivation

I'm using a custom train script, instead of the one provided in classy vision, and it seems silly having to implement a feature that belongs to a specific task in a generic training pipeline.

Effectively, this can be achieved by loading the checkpoint in the `from_config` method in the FineTuningTask class.

Happy to do a PR for this.

**Comment by mannatsingh** [comment]
@miguelvr That's a good point. 

The reason that we don't have the loading checkpoint aspect inside the task is because there can be situations where users have checkpoints which aren't saved in their local filesystems (s3, for example), and the checkpoint saving / loading isn't part of the task. 

At the same time, even after this change, those users can continue to call `set_pretrained_checkpoint` instead of relying on `from_config`. If we do go your suggested route, the next obvious question is why we also don't support this for regular checkpoints.

 @vreis , @aadcock do you have any thoughts? This is @miguelvr 's PR for reference - https://github.com/facebookresearch/ClassyVision/pull/341.

**Comment by mannatsingh** [comment]
Discussed with @vreis , we should have better abstractions for checkpointing so that users can change how and where checkpoints are loaded from and stored. For now, we can go ahead with #341 since it doesn't break anything - we can update the internal implementation of `from_config` once we update the checkpointing API.

**Comment by vreis** [comment]
I like the PR, thanks @miguelvr!
To clarify Mannat's point: there are many ways of loading checkpoints and we didn't want to be prescriptive about that in `from_config` (load_checkpoint right now only works for local files).

Long-term, I think we'll end up introducing a `ClassyCheckpoint` abstraction to allow loading from many different sources. And in that case we can just update the implementation to use that instead.

**Comment by miguelvr** [comment]
@mannatsingh @vreis At first I made it a requirement to have the `pretrained_checkpoint` argument in the config and I checked for it in the `from_config` call.

However, my current approach aims to be backwards compatible, enabling both ways of setting up the checkpoint: from the config or by setting it with `set_pretrained_checkpoint`. Only at the `prepare` stage an error will be thrown.

I agree with you when it comes to supporting normal checkpoints. I had to bend over backwards to load a simple imagenet checkpoint from a pretrained pytorch model. The custom state dicts in classy vision make it more complicated to start from the weights of an external source.

Let me know if I can help with that :)
