### ISSUE TITLE
How to enable the MixupTransform in my training?

### ISSUE THREAD

**Issue by YaqiLYU** [facebookresearch/ClassyVision#598]
MixupTransform is not registered in transform. How can I use it in my training?

**Comment by mannatsingh** [comment]
Since mixup works differently from other transforms (it doesn't work on a single image), it isn't part of the regular `ClassyTransform`s. 
Instead, it can be enabled using [`ClassificationTask.set_mixup_transform(mixup_transform)`](https://classyvision.ai/api/tasks.html#classy_vision.tasks.ClassificationTask.set_mixup_transform). 

If you're running your code through a configuration, you need to add the following section to the config dictionary - 
```
{
    ...
    "mixup": {"alpha": xyz, "num_classes": abc}
    ...
}
```

**Comment by YaqiLYU** [comment]
Got it! Thanks.
