### ISSUE TITLE
how to training myself video ?

### ISSUE THREAD

**Issue by siyangbing** [facebookresearch/ClassyVision#612]
## ❓ Questions and Help

Before creating an issue, please go over our [Tutorials](https://classyvision.ai/tutorials) and [API Reference](https://classyvision.ai/api). If you cannot find the information you are looking for, please enquire in Classy Vision's `#help` [slack](https://classyvision.slack.com) channel before creating an issue.

I want to train my own video recognition, including screwing the bottle cap to the right and screwing the bottle cap to the left. Is this possible? How many videos need to be taken to ensure the training effect? Can I directly use the configuration of ucf101 for training?

please help me @mannatsingh

**Comment by mannatsingh** [comment]
@siyangbing yes, you can train your own dataset with Classy Vision. 

>I want to train my own video recognition, including screwing the bottle cap to the right and screwing the bottle cap to the left. Is this possible? How many videos need to be taken to ensure the training effect? Can I directly use the configuration of ucf101 for training?

Unfortunately, I can't help you with these questions since there is no simple answer for this. You need to run experiments to see how much data is needed and what the configuration needs to be. I would recommend reading up on video classification through research papers / course lectures to get a general idea.
