### ISSUE TITLE
Could you please provide a dockerfile to help build this awesome repo~

### ISSUE THREAD

**Issue by shinianzhihou** [facebookresearch/ClassyVision#679]
Could you please provide a dockerfile to help build this awesome repo~

**Comment by mannatsingh** [comment]
Hi @shinianzhihou we don't have a dockerfile since the setup is very straightforward - 
- Install Python 3.6.2+
- Install `PyTorch` and `torchvision` (and optionally CUDA) using https://pytorch.org/get-started/locally/
- Install Classy Vision using `pip install classy_vision`

If you're having any trouble, please let me know!

**Comment by shinianzhihou** [comment]
OK，thanks，I mainly want to build this project in my sever. I will make one, thanks~发自我的华为手机-------- 原始邮件 --------发件人： Mannat Singh <notifications@github.com>日期： 2021年1月9日周六 凌晨4:37收件人： facebookresearch/ClassyVision <ClassyVision@noreply.github.com>抄送： Nian Shi <15155297566@163.com>, Mention <mention@noreply.github.com>主    题： Re: [facebookresearch/ClassyVision] Could you please provide a dockerfile to help build this awesome repo~ (#679)
Hi @shinianzhihou we don't have a dockerfile since the setup is very straightforward -
Install Python 3.6.2+Install PyTorch and torchvision (and optionally CUDA) using https://pytorch.org/get-started/locally/Install Classy Vision using pip install classy_vision
If you're having any trouble, please let me know!
